FROM php:8.4-apache

# Instala extensões necessárias
RUN apt-get update && apt-get install -y \
    libcurl4-openssl-dev \
    && docker-php-ext-install curl pdo pdo_mysql

# Habilita mod_rewrite do Apache
RUN a2enmod rewrite

# Copia o código pro container
COPY . /var/www/html/

# Permissões
RUN chown -R www-data:www-data /var/www/html